package main

import (
	"fmt"

	. "github.com/donutnomad/gg"
)

func main() {
	gen := New()
	gen.SetPackage("example")
	gen.SetHeader("Code generated by example. DO NOT EDIT.")

	// 引用外部包
	types := gen.P("github.com/example/types")
	fmtPkg := gen.P("fmt")

	// 示例 1: 基本类型的切片
	gen.Body().NewVar().AddField("numbers", Slice("int",
		Lit(1), Lit(2), Lit(3), Lit(4), Lit(5),
	))

	gen.Body().AddLine()

	// 示例 2: 字符串切片
	gen.Body().NewVar().AddField("fruits", Slice("string",
		Lit("apple"),
		Lit("banana"),
		Lit("cherry"),
	))

	gen.Body().AddLine()

	// 示例 3: 使用 PackageRef 的切片
	gen.Body().NewVar().AddField("users", Slice(types.Type("User"),
		S("types.User{ID: 1, Name: \"Alice\"}"),
		S("types.User{ID: 2, Name: \"Bob\"}"),
		S("types.User{ID: 3, Name: \"Charlie\"}"),
	))

	gen.Body().AddLine()

	// 示例 4: 指针类型的切片
	gen.Body().NewVar().AddField("configs", Slice(types.Ptr("Config"),
		S("&types.Config{Name: \"dev\"}"),
		S("&types.Config{Name: \"prod\"}"),
		S("nil"),
	))

	gen.Body().AddLine()

	// 示例 5: 固定大小数组
	gen.Body().NewVar().AddField("matrix", Array(3, "[]int",
		Slice("int", Lit(1), Lit(2), Lit(3)),
		Slice("int", Lit(4), Lit(5), Lit(6)),
		Slice("int", Lit(7), Lit(8), Lit(9)),
	))

	gen.Body().AddLine()

	// 示例 6: 在函数中使用
	fn := gen.Body().NewFunction("GetDefaultUsers")
	fn.Return(types.Slice("User"))
	fn.AddBody(
		Return(Slice(types.Type("User"),
			S("types.User{ID: 1, Name: \"Default User 1\"}"),
			S("types.User{ID: 2, Name: \"Default User 2\"}"),
		)),
	)

	gen.Body().AddLine()

	// 示例 7: 动态添加元素
	s := Slice("string")
	items := []string{"one", "two", "three", "four"}
	for _, item := range items {
		s.AddElement(Lit(item))
	}
	gen.Body().NewVar().AddField("dynamicSlice", s)

	gen.Body().AddLine()

	// 示例 8: 在函数参数中使用
	gen.Body().NewFunction("ProcessItems").
		AddParameter("items", types.Slice("Item")).
		AddResult("", "error").
		AddBody(
			S("for _, item := range items {"),
			S("    %s", fmtPkg.Call("Println", S("item"))),
			S("}"),
			Return(S("nil")),
		)

	// 输出生成的代码
	fmt.Println(gen.String())
}
